spring:
  application:
    name: kafka-repeat-error
  kafka:
    bootstrap-servers: localhost:9092 # Kafka broker address (matches the Docker Compose service name and port)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      properties:
        telemetry:
          enabled: false

    template:
      topic-1: topic-1 # Default Kafka topic to use if not specified explicitly
      topic-2: topic-2 # Default Kafka topic to use if not specified explicitly
    listener:
      missing-topics-fatal: false # Prevent application failure if topics are missing

server:
  port: 8085
